### ISSUE TITLE
Bug: json.decoder.JSONDecodeError: Invalid \escape

### ISSUE THREAD

**Issue by metropolik** [pytorch/kineto#336] opened 2021-07-06 12:01 UTC
Hi, I've been following this tutorial 
https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html
but I'm getting this exception
```
W0706 13:29:50.962253 10484 loader.py:105] Failed to parse profile data for Run 20210706-132937 on MY_PC_NAME. Exception=Invalid \escape: line 12 column 64 (char 365)
Traceback (most recent call last):
  File "path_to_python\lib\site-packages\torch_tb_profiler\profiler\data.py", line 109, in _preprocess_file
    trace_json = json.loads(data)
  File "path_to_python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "path_to_python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "path_to_python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 12 column 64 (char 365)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path_to_python\lib\site-packages\torch_tb_profiler\profiler\data.py", line 114, in _preprocess_file
    trace_json = json.loads(data, strict=False)
  File "path_to_python\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "path_to_python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "path_to_python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 12 column 64 (char 365)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path_to_python\lib\site-packages\torch_tb_profiler\profiler\loader.py", line 92, in _process_data
    data = RunProfileData.parse(self.run_dir, worker, span, path, self.caches)
  File "path_to_python\lib\site-packages\torch_tb_profiler\profiler\data.py", line 80, in parse
    trace_path, trace_json = RunProfileData._preprocess_file(caches, io.join(run_dir, path))
  File "path_to_python\lib\site-packages\torch_tb_profiler\profiler\data.py", line 120, in _preprocess_file
    trace_json = json.loads(fout.getvalue())
  File "path_to_python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "path_to_python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "path_to_python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 12 column 64 (char 365)
WARNING: Logging before flag parsing goes to stderr.
W0706 13:29:50.974256  3216 loader.py:105] Failed to parse profile data for Run 20210706-132937 on MY_PC_NAME. Exception=Invalid \escape: line 12 column 64 (char 369)
Traceback (most recent call last):
  File "path_to_python\lib\site-packages\torch_tb_profiler\profiler\data.py", line 109, in _preprocess_file
    trace_json = json.loads(data)
  File "path_to_python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "path_to_python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "path_to_python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 12 column 64 (char 369)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path_to_python\lib\site-packages\torch_tb_profiler\profiler\data.py", line 114, in _preprocess_file
    trace_json = json.loads(data, strict=False)
  File "path_to_python\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "path_to_python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "path_to_python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 12 column 64 (char 369)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path_to_python\lib\site-packages\torch_tb_profiler\profiler\loader.py", line 92, in _process_data
    data = RunProfileData.parse(self.run_dir, worker, span, path, self.caches)
  File "path_to_python\lib\site-packages\torch_tb_profiler\profiler\data.py", line 80, in parse
    trace_path, trace_json = RunProfileData._preprocess_file(caches, io.join(run_dir, path))
  File "path_to_python\lib\site-packages\torch_tb_profiler\profiler\data.py", line 120, in _preprocess_file
    trace_json = json.loads(fout.getvalue())
  File "path_to_python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "path_to_python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "path_to_python\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 12 column 64 (char 369)
I0706 13:29:50.984259  6328 plugin.py:362] Run 20210706-132937 loaded
I0706 13:29:50.984259  7160 plugin.py:327] Add run 20210706-132937
W0706 13:32:36.983650 11828 security_validator.py:46] In 3.0, this warning will become an error:
Requires default-src for Content-Security-Policy
W0706 13:33:41.825928  5240 security_validator.py:46] In 3.0, this warning will become an error:
Requires default-src for Content-Security-Policy
```
Package | Version | Source
--------- | -------- | --------
torch-tb-profiler | 0.2.0 | pip
tensorboard | 2.5.0 | conda-forge
tensorboard-data-server | 0.6.0 |conda-forge
tensorboard-plugin-wit | 1.8.0 | conda-forge
pytorch | 1.9.0 py3.9_cuda11.1_cudnn8_0 | pytorch

Anyone know how to fix this?
I'm setting the torch.utils.tensorboard.SummaryWriter output logdir as the same as the torch.profiler.tensorboard_trace_handler logdir. Tensorboard uses as logdir this directory's parent. Hope that's ok.

The profiler inside tensorboard shows the correct run in the drop-down menu, but the loading animation plays infinitely.

**Comment by metropolik** [comment] 2021-07-06 12:19
Looks like this is not a bug of `torch-tb-profiler` but `pytorch`.
Looking into one of the json files reveals that the Call stack paths are not properly escaped.
`\site-packages\torch\autograd\profiler.py(611)`
I'll reopen an issue in the pytorch repo

**Comment by metropolik** [comment] 2021-07-06 12:45
pytorch seems to use this library to export its call stacks?
I could only follow the problem down to
https://github.com/pytorch/pytorch/blob/11aa5e4f663e74cfed74b268f356c58a6d47a0cf/torch/autograd/profiler.py#L201
but since `args` which contains the faulty paths is just an argument it must come from somewhere higher up

Here is an example of what causes the problem:
```
"Input Dims": [[], [], [], [], [], []], "Call stack": "C:\Users\user\python\lib\site-packages\torch\autograd\profiler.py(611): __init__;C:\Users\user\python\lib\site-packages\torch\optim\optimizer.py(205): zero_grad;C:\Users\user\source.py(101): step;C:\Users\user\source.py(185): run;C:\Users\user\source.py(193): <module>", "Input type": ["GenericList", "Int", "", "", "Bool", ""]
```

**Comment by metropolik** [comment] 2021-07-06 13:29
For anyone else looking for a workaround:
Change line 114 in `'\path_to_python_installation\Lib\site-packages\torch_tb_profiler\profiler\data.py'`
to
`trace_json = json.loads(data.replace(b"\\", b"\\\\"), strict=False)`
This works for me as a dirty workaround

**Comment by guotuofeng** [comment] 2021-07-06 23:46
duplicated with https://github.com/pytorch/pytorch/issues/60187, the bug should be fixed in next release.

**Closed** 2021-07-06 23:47 UTC
Labels: bug, duplicate, profiler

**Comment by qideng7** [comment] 2022-10-13 04:08
Same issue pops up with torch-tb-profiler=0.4.0, but the cause is different from @metropolik mentioned. It appears to be the "\\" in module name:
`"name": "lib\site-packages\torch\autograd\profiler.py(205): _start_trace", "pid": 19196, "tid": 9096,`
That workaround could still work.
| package  | version | build | source |
| ------------- | ------------- | ------------- | ------------- |
| pytorch  | 1.12.1 | py3.9_cuda11.6_cudnn8_0  | pytorch
| tensorboard | 2.10.1 | pypi_0 | pypi |
| tensorboard-data-server |   0.6.1 | pypi_0 | pypi |
| tensorboard-plugin-wit |    1.8.1 | pypi_0 | pypi |
| torch-tb-profiler | 0.4.0 | pypi_0 | pypi |

**Comment by sdake** [comment] 2023-08-30 02:41
This may (or may not) be related: https://github.com/pytorch/pytorch/pull/60842/files
