### ISSUE TITLE
Chrome tracing json file fail to load because of unexpected string encoding

### ISSUE THREAD

**Issue by gaoteng-git** [pytorch/kineto#80] opened 2021-02-24 12:24 UTC
When using pytorch profiler with kineto enabled to profile model such as torchvision.alexnet, the dumped chrome tracing file can't be loaded by chrome://tracing. 
It is caused by string with unexpected encoding in the file:
![image](https://user-images.githubusercontent.com/10429114/108999925-f9755b80-76dd-11eb-916c-95465a1ce77c.png)

The running environment:
OS version: Ubuntu 18.04; Python: 3.8.5; CUDA: 11.1
PyTorch install: https://download.pytorch.org/whl/test/cu111/torch-1.8.0%2Bcu111-cp38-cp38-linux_x86_64.whl
Torchvision install: https://download.pytorch.org/whl/test/cu111/torchvision-0.9.0%2Bcu111-cp38-cp38-linux_x86_64.whl

The corrupted string will cause the dumped chrome tracing file fail to load. So it will cause our tensorboard plugin fail to show it.
It also makes PyTorch profiler CLI print confused to user. You could see the corrupted event is shown as empty string.
![image](https://user-images.githubusercontent.com/10429114/109000116-3a6d7000-76de-11eb-8780-fc44cdc61a0e.png)

**Comment by gdankel** [comment] 2021-02-26 05:35
@gaoteng-git I see what the issue is looking at your screenshot. Thanks! Will fix.

**Comment by gdankel** [comment] 2021-03-05 18:16
This should be resolved in latest nightly - @gaoteng-git can you confirm as well?

**Comment by gaoteng-git** [comment] 2021-03-06 03:30
> This should be resolved in latest nightly - @gaoteng-git can you confirm as well?

@gdankel Great! It works now!

**Closed** 2021-03-16 00:07 UTC
Labels: bug

**Comment by TianhaoFu** [comment] 2021-06-22 07:44
> > This should be resolved in latest nightly - @gaoteng-git can you confirm as well?
> 
> @gdankel Great! It works now!

Hi, did you work? what's your version of torch.
